-- ------------------------- info -------------------------
-- @@ver: 1_000_002
-- @@info: add flow_form、flow_form_table
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "flow_form" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "catagory_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "no" varchar(255) NOT NULL,
  "type" smallint NOT NULL,
  "status" smallint NOT NULL,
  "sort" integer NULL DEFAULT 0,
  "icon" varchar(255) NULL DEFAULT NULL,
  "remark" varchar(255) NULL DEFAULT NULL,
  "table_name" varchar(255) NULL DEFAULT NULL,
  "data_config" jsonb NULL,
  "config" jsonb NULL,
  "table_config" jsonb NULL,
  "flow_process_id" integer NULL DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) NULL DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) NULL DEFAULT NULL,
  "upd_name" varchar(255) NULL DEFAULT NULL,
  "upd_host" varchar(255) NULL DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "flow_form" IS 'FLOW-流程表单';
COMMENT ON COLUMN "flow_form"."id" IS 'ID';
COMMENT ON COLUMN "flow_form"."catagory_id" IS '流程分类ID';
COMMENT ON COLUMN "flow_form"."name" IS '名称';
COMMENT ON COLUMN "flow_form"."no" IS '编码';
COMMENT ON COLUMN "flow_form"."type" IS '表单类型:1设计表单/2系统表单';
COMMENT ON COLUMN "flow_form"."status" IS '状态：1启用/2禁止';
COMMENT ON COLUMN "flow_form"."sort" IS '排序ID';
COMMENT ON COLUMN "flow_form"."icon" IS '图标';
COMMENT ON COLUMN "flow_form"."remark" IS '备注';
COMMENT ON COLUMN "flow_form"."table_name" IS '表名';
COMMENT ON COLUMN "flow_form"."data_config" IS '数据库配置';
COMMENT ON COLUMN "flow_form"."config" IS '表单配置';
COMMENT ON COLUMN "flow_form"."table_config" IS '列表配置';
COMMENT ON COLUMN "flow_form"."flow_process_id" IS '流程ID';
COMMENT ON COLUMN "flow_form"."crt_time" IS '创建时间';
COMMENT ON COLUMN "flow_form"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "flow_form"."crt_name" IS '创建用户';
COMMENT ON COLUMN "flow_form"."crt_host" IS '创建IP';
COMMENT ON COLUMN "flow_form"."upd_time" IS '更新时间';
COMMENT ON COLUMN "flow_form"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "flow_form"."upd_name" IS '更新用户';
COMMENT ON COLUMN "flow_form"."upd_host" IS '更新IP';
COMMENT ON COLUMN "flow_form"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "flow_form__upd_time" ON "flow_form";
CREATE TRIGGER "flow_form__upd_time" BEFORE UPDATE ON "flow_form" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

CREATE TABLE IF NOT EXISTS "flow_form_table" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "flow_form_id" integer NOT NULL,
  "sort" integer NULL DEFAULT 0,
  "table_name" varchar(255) NOT NULL,
  "data_config" jsonb NULL,
  "remark" varchar(255) NULL DEFAULT NULL,
  "foreign_key" varchar(255) NULL DEFAULT NULL,
  "reference_key" varchar(255) NULL DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) NULL DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) NULL DEFAULT NULL,
  "upd_name" varchar(255) NULL DEFAULT NULL,
  "upd_host" varchar(255) NULL DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "flow_form_table" IS 'FLOW-流程表单关联表';
COMMENT ON COLUMN "flow_form_table"."id" IS 'ID';
COMMENT ON COLUMN "flow_form_table"."flow_form_id" IS '流程表单ID';
COMMENT ON COLUMN "flow_form_table"."sort" IS '排序ID';
COMMENT ON COLUMN "flow_form_table"."table_name" IS '表名';
COMMENT ON COLUMN "flow_form_table"."data_config" IS '数据库配置';
COMMENT ON COLUMN "flow_form_table"."remark" IS '备注';
COMMENT ON COLUMN "flow_form_table"."foreign_key" IS '外键字段';
COMMENT ON COLUMN "flow_form_table"."reference_key" IS '关联主键';
COMMENT ON COLUMN "flow_form_table"."crt_time" IS '创建时间';
COMMENT ON COLUMN "flow_form_table"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "flow_form_table"."crt_name" IS '创建用户';
COMMENT ON COLUMN "flow_form_table"."crt_host" IS '创建IP';
COMMENT ON COLUMN "flow_form_table"."upd_time" IS '更新时间';
COMMENT ON COLUMN "flow_form_table"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "flow_form_table"."upd_name" IS '更新用户';
COMMENT ON COLUMN "flow_form_table"."upd_host" IS '更新IP';
COMMENT ON COLUMN "flow_form_table"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "flow_form_table__upd_time" ON "flow_form_table";
CREATE TRIGGER "flow_form_table__upd_time" BEFORE UPDATE ON "flow_form_table" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

ALTER TABLE "flow_process" ADD COLUMN "form_type" smallint NULL DEFAULT NULL;
COMMENT ON COLUMN "flow_process"."form_type" IS '表单类型';

ALTER TABLE "flow_process" ADD COLUMN "form_id" integer NULL DEFAULT NULL;
COMMENT ON COLUMN "flow_process"."form_id" IS '自定义表单ID';

