package com.faber.api.flow.form.biz;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.Objects;
import java.math.BigDecimal;

import com.faber.core.exception.BuzzException;
import com.faber.api.flow.form.vo.ret.TableColumnVo;
import com.faber.api.flow.form.vo.ret.TableInfoVo;

/** 方言隔离入口，优先覆盖动态流程表的基础建表语句。 */
enum FlowFormDdlDialect {
    MYSQL,
    POSTGRESQL;

    static FlowFormDdlDialect from(Connection connection) throws SQLException {
        String productName = connection.getMetaData().getDatabaseProductName();
        String normalizedName = productName == null ? "" : productName.toLowerCase(Locale.ROOT);
        if (normalizedName.contains("mysql")) {
            return MYSQL;
        }
        if (normalizedName.contains("postgresql")) {
            return POSTGRESQL;
        }
        throw new BuzzException("流程表单动态建表暂不支持数据库: " + productName);
    }

    String quoteIdentifier(String identifier, String label) {
        String safeIdentifier = FlowFormSqlUtils.requireIdentifier(identifier, label);
        if (this == POSTGRESQL && safeIdentifier.length() > 63) throw new BuzzException(label + "长度不能超过63");
        return this == MYSQL ? "`" + safeIdentifier + "`" : "\"" + safeIdentifier + "\"";
    }

    List<String> createFormTableStatements(String tableName, String comment) {
        String quotedTableName = quoteIdentifier(FlowFormSqlUtils.requireTableName(tableName), "表名");
        if (this == MYSQL) {
            String sql = "CREATE TABLE " + quotedTableName + " (\n" +
                    "  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',\n" +
                    "  `flow_instance_id` bigint(20) DEFAULT NULL COMMENT '流程实例ID',\n" +
                    "  `tenant_id` varchar(32) DEFAULT NULL COMMENT '租户ID',\n" +
                    "  `crt_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n" +
                    "  `crt_user` varchar(32) NOT NULL COMMENT '创建用户ID',\n" +
                    "  `upd_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',\n" +
                    "  `upd_user` varchar(32) DEFAULT NULL COMMENT '更新用户ID',\n" +
                    "  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',\n" +
                    "  PRIMARY KEY (`id`)\n" +
                    ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=" +
                    FlowFormSqlUtils.quoteDdlLiteral(comment == null ? "" : comment, "表注释");
            return List.of(sql);
        }

        List<String> statements = new ArrayList<>(10);
        statements.add("CREATE TABLE " + quotedTableName + " (\n" +
                "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                "  \"flow_instance_id\" BIGINT,\n" +
                "  \"tenant_id\" VARCHAR(32),\n" +
                "  \"crt_time\" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
                "  \"crt_user\" VARCHAR(32) NOT NULL,\n" +
                "  \"upd_time\" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n" +
                "  \"upd_user\" VARCHAR(32),\n" +
                "  \"deleted\" BOOLEAN NOT NULL DEFAULT FALSE\n" +
                ")");
        statements.add("COMMENT ON TABLE " + quotedTableName + " IS " +
                FlowFormSqlUtils.quotePostgresDdlLiteral(comment == null ? "" : comment, "表注释"));
        statements.add(commentOnColumn(quotedTableName, "id", "ID"));
        statements.add(commentOnColumn(quotedTableName, "flow_instance_id", "流程实例ID"));
        statements.add(commentOnColumn(quotedTableName, "tenant_id", "租户ID"));
        statements.add(commentOnColumn(quotedTableName, "crt_time", "创建时间"));
        statements.add(commentOnColumn(quotedTableName, "crt_user", "创建用户ID"));
        statements.add(commentOnColumn(quotedTableName, "upd_time", "更新时间"));
        statements.add(commentOnColumn(quotedTableName, "upd_user", "更新用户ID"));
        statements.add(commentOnColumn(quotedTableName, "deleted", "是否删除"));
        return List.copyOf(statements);
    }

    String databaseType() {
        return this == MYSQL ? "mysql" : "postgre";
    }

    static String normalizedType(String type) {
        if (type == null) throw new BuzzException("字段类型不能为空");
        return switch (type.toLowerCase(Locale.ROOT).trim()) {
            case "character varying" -> "varchar";
            case "character", "bpchar" -> "char";
            case "integer", "int4" -> "int";
            case "int8" -> "bigint";
            case "int2" -> "smallint";
            case "float4" -> "real";
            case "float8" -> "double precision";
            case "bool" -> "boolean";
            case "timestamp without time zone" -> "timestamp";
            default -> type.toLowerCase(Locale.ROOT).trim();
        };
    }

    void normalizeColumn(TableColumnVo column) {
        String type = normalizedType(column.getDataType());
        column.setDataType(type);
        if (!Set.of("char", "varchar", "binary", "varbinary").contains(type)) column.setLength(null);
        if (!Set.of("decimal", "numeric").contains(type)) {
            column.setPrecision(null);
            column.setScale(null);
        }
        column.setDefaultExpression(false);
        String value = column.getDefaultValue();
        if (value == null) return;
        if (this == MYSQL) {
            if (column.getExtra() != null && column.getExtra().toLowerCase(Locale.ROOT).contains("default_generated")
                    && !"CURRENT_TIMESTAMP".equalsIgnoreCase(value) && !"CURRENT_TIMESTAMP()".equalsIgnoreCase(value)) {
                column.setDefaultExpression(true);
            }
            if (Set.of("datetime", "timestamp").contains(type) && "CURRENT_TIMESTAMP()".equalsIgnoreCase(value)) column.setDefaultValue("CURRENT_TIMESTAMP");
            return;
        }
        if ("now()".equalsIgnoreCase(value) || "CURRENT_TIMESTAMP".equalsIgnoreCase(value)) {
            if (Set.of("datetime", "timestamp").contains(type)) {
                column.setDefaultValue("CURRENT_TIMESTAMP");
            } else {
                column.setDefaultExpression(true);
            }
        } else if (value.matches("(?s)'(?:[^']|'')*'(?:::[a-zA-Z ]+(?:\\(\\d+(?:,\\d+)?\\))?)?")) {
            int end = value.lastIndexOf("'");
            column.setDefaultValue(value.substring(1, end).replace("''", "'"));
        } else if (value.matches("[+-]?(?:[0-9]+(?:\\.[0-9]*)?|\\.[0-9]+)(?:[eE][+-]?[0-9]+)?")
                || "true".equalsIgnoreCase(value) || "false".equalsIgnoreCase(value)) {
            column.setDefaultValue(value);
        } else {
            column.setDefaultExpression(true);
        }
    }

    List<String> columnStatements(String table, TableColumnVo column, boolean update, TableColumnVo existing) {
        String quotedTable = quoteIdentifier(FlowFormSqlUtils.requireTableName(table), "表名");
        String name = quoteIdentifier(column.getField(), "字段名");
        String type = columnType(column);
        String nullable = column.getNullable();
        if (nullable != null && !"YES".equalsIgnoreCase(nullable) && !"NO".equalsIgnoreCase(nullable)) {
            throw new BuzzException("nullable只能是YES或NO");
        }
        boolean required = "NO".equalsIgnoreCase(nullable);
        String defaultSql = defaultSql(column);
        String comment = column.getComment() == null ? "" : column.getComment();
        validateText(comment, "字段注释");
        if (this == MYSQL) {
            String definition = type + (required ? " NOT NULL" : " NULL")
                    + (defaultSql == null ? "" : " DEFAULT " + defaultSql)
                    + " COMMENT " + FlowFormSqlUtils.quoteDdlLiteral(comment, "字段注释");
            return List.of("ALTER TABLE " + quotedTable + (update ? " MODIFY COLUMN " : " ADD COLUMN ") + name + " " + definition);
        }
        List<String> statements = new ArrayList<>();
        String prefix = "ALTER TABLE " + quotedTable + " ALTER COLUMN " + name;
        if (update) {
            // 先移除旧默认值，避免旧默认值阻止兼容的类型变更；全部语句在同一事务执行。
            statements.add(prefix + " DROP DEFAULT");
            if (!sameColumnType(column, existing)) statements.add(prefix + " TYPE " + type);
            statements.add(prefix + (required ? " SET NOT NULL" : " DROP NOT NULL"));
            if (defaultSql != null) statements.add(prefix + " SET DEFAULT " + defaultSql);
        } else {
            statements.add("ALTER TABLE " + quotedTable + " ADD COLUMN " + name + " " + type
                    + (required ? " NOT NULL" : " NULL") + (defaultSql == null ? "" : " DEFAULT " + defaultSql));
        }
        statements.add(commentOnColumn(quotedTable, column.getField(), comment));
        return List.copyOf(statements);
    }

    private boolean sameColumnType(TableColumnVo column, TableColumnVo existing) {
        if (existing == null) return false;
        String type = normalizedType(column.getDataType());
        if (!type.equals(normalizedType(existing.getDataType()))) return false;
        if (Set.of("varchar", "char").contains(type)) return Objects.equals(column.getLength(), existing.getLength());
        if (Set.of("numeric", "decimal").contains(type)) return Objects.equals(column.getPrecision(), existing.getPrecision())
                && Objects.equals(column.getScale(), existing.getScale());
        return true;
    }

    private String columnType(TableColumnVo column) {
        String type = normalizedType(column.getDataType());
        Set<String> allowed = this == MYSQL
                ? Set.of("varchar", "char", "varbinary", "binary", "int", "bigint", "smallint", "tinyint", "mediumint", "decimal", "numeric", "float", "double", "text", "date", "datetime", "timestamp", "json")
                : Set.of("varchar", "char", "int", "bigint", "smallint", "numeric", "decimal", "real", "double precision", "text", "date", "timestamp", "boolean", "json", "jsonb");
        if (!allowed.contains(type)) throw new BuzzException("当前数据库不支持字段类型: " + type);
        if (Set.of("char", "varchar", "binary", "varbinary").contains(type)) {
            range(column.getLength(), 1, 65535, "字段长度");
            return type + "(" + column.getLength() + ")";
        }
        if (Set.of("decimal", "numeric").contains(type)) {
            range(column.getPrecision(), 1, this == MYSQL ? 65 : 1000, "字段精度");
            range(column.getScale(), 0, this == MYSQL ? 30 : 1000, "字段小数位");
            if (column.getScale() > column.getPrecision()) throw new BuzzException("小数位不能大于字段精度");
            return type + "(" + column.getPrecision() + "," + column.getScale() + ")";
        }
        return type;
    }

    private String defaultSql(TableColumnVo column) {
        String value = column.getDefaultValue();
        if (value == null) return null;
        validateText(value, "默认值");
        String type = normalizedType(column.getDataType());
        if (this == MYSQL && Set.of("text", "json").contains(type)) throw new BuzzException("MySQL TEXT/JSON字段暂不支持默认值");
        if (Set.of("datetime", "timestamp").contains(type) && "CURRENT_TIMESTAMP".equalsIgnoreCase(value)) return "CURRENT_TIMESTAMP";
        if (Set.of("int", "bigint", "smallint", "tinyint", "mediumint", "decimal", "numeric", "float", "double", "real", "double precision").contains(type)) {
            if (!value.matches("[+-]?(?:[0-9]+(?:\\.[0-9]*)?|\\.[0-9]+)(?:[eE][+-]?[0-9]+)?")) throw new BuzzException("数字字段默认值必须是数字");
            BigDecimal number = new BigDecimal(value);
            if (Set.of("int", "bigint", "smallint", "tinyint", "mediumint").contains(type) && number.stripTrailingZeros().scale() > 0) throw new BuzzException("整数字段默认值必须是整数");
            return value;
        }
        if ("boolean".equals(type)) {
            if ("true".equalsIgnoreCase(value) || "1".equals(value)) return "TRUE";
            if ("false".equalsIgnoreCase(value) || "0".equals(value)) return "FALSE";
            throw new BuzzException("布尔字段默认值必须是true或false");
        }
        return this == MYSQL ? FlowFormSqlUtils.quoteDdlLiteral(value, "默认值") : FlowFormSqlUtils.quotePostgresDdlLiteral(value, "默认值");
    }

    private static void range(Integer value, int min, int max, String label) {
        if (value == null || value < min || value > max) throw new BuzzException(label + "必须在" + min + "到" + max + "之间");
    }

    private static void validateText(String value, String label) {
        if (value.length() > 255) throw new BuzzException(label + "长度不能超过255");
    }

    private String commentOnColumn(String quotedTableName, String columnName, String comment) {
        return "COMMENT ON COLUMN " + quotedTableName + "." + quoteIdentifier(columnName, "字段名") + " IS " +
                FlowFormSqlUtils.quotePostgresDdlLiteral(comment, "字段注释");
    }
    /** JDBC 元数据用于两库结构检查，避免 PostgreSQL 执行 MySQL information_schema 查询。 */
    static TableInfoVo tableStructure(Connection conn, String table) throws SQLException {
        FlowFormSqlUtils.requireTableName(table);
        String schema = FlowFormDdlDialect.from(conn) == FlowFormDdlDialect.POSTGRESQL ? conn.getSchema() : null;
        String catalog = conn.getCatalog();
        TableInfoVo info = new TableInfoVo();
        info.setTableName(table);
        info.setDatabaseType(FlowFormDdlDialect.from(conn).databaseType());
        info.setExist(false);
        try (ResultSet tables = conn.getMetaData().getTables(catalog, schema, table, new String[] { "TABLE" })) {
            while (tables.next()) {
                if (table.equals(tables.getString("TABLE_NAME"))) {
                    info.setExist(true);
                    info.setTableComment(tables.getString("REMARKS"));
                    break;
                }
            }
        }
        List<TableColumnVo> columns = new ArrayList<>();
        if (Boolean.TRUE.equals(info.getExist())) {
            try (ResultSet rs = conn.getMetaData().getColumns(catalog, schema, table, null)) {
                while (rs.next()) {
                    if (!table.equals(rs.getString("TABLE_NAME"))) continue;
                    TableColumnVo column = new TableColumnVo();
                    column.setField(rs.getString("COLUMN_NAME"));
                    column.setDataType(rs.getString("TYPE_NAME"));
                    column.setType(rs.getString("TYPE_NAME"));
                    column.setLength(rs.getInt("COLUMN_SIZE"));
                    column.setPrecision(rs.getInt("COLUMN_SIZE"));
                    column.setScale(rs.getInt("DECIMAL_DIGITS"));
                    column.setNullable(rs.getString("IS_NULLABLE"));
                    column.setComment(rs.getString("REMARKS"));
                    columns.add(column);
                }
            }
            try (ResultSet keys = conn.getMetaData().getPrimaryKeys(catalog, schema, table)) {
                if (keys.next()) info.setPkField(keys.getString("COLUMN_NAME"));
            }
        }
        info.setColumns(columns);
        return info;
    }

}
