package com.faber.api.flow.form.biz;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import com.faber.core.exception.BuzzException;

/** 方言隔离入口，优先覆盖动态流程表的基础建表语句。 */
enum FlowFormDdlDialect {
    MYSQL,
    POSTGRESQL;

    static FlowFormDdlDialect from(Connection connection) throws SQLException {
        String productName = connection.getMetaData().getDatabaseProductName();
        String normalizedName = productName == null ? "" : productName.toLowerCase(Locale.ROOT);
        if (normalizedName.contains("mysql")) {
            return MYSQL;
        }
        if (normalizedName.contains("postgresql")) {
            return POSTGRESQL;
        }
        throw new BuzzException("流程表单动态建表暂不支持数据库: " + productName);
    }

    String quoteIdentifier(String identifier, String label) {
        String safeIdentifier = FlowFormSqlUtils.requireIdentifier(identifier, label);
        return this == MYSQL ? "`" + safeIdentifier + "`" : "\"" + safeIdentifier + "\"";
    }

    List<String> createFormTableStatements(String tableName, String comment) {
        String quotedTableName = quoteIdentifier(FlowFormSqlUtils.requireTableName(tableName), "表名");
        if (this == MYSQL) {
            String sql = "CREATE TABLE " + quotedTableName + " (\n" +
                    "  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',\n" +
                    "  `flow_instance_id` bigint(20) DEFAULT NULL COMMENT '流程实例ID',\n" +
                    "  `tenant_id` varchar(32) DEFAULT NULL COMMENT '租户ID',\n" +
                    "  `crt_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n" +
                    "  `crt_user` varchar(32) NOT NULL COMMENT '创建用户ID',\n" +
                    "  `upd_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',\n" +
                    "  `upd_user` varchar(32) DEFAULT NULL COMMENT '更新用户ID',\n" +
                    "  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',\n" +
                    "  PRIMARY KEY (`id`)\n" +
                    ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=" +
                    FlowFormSqlUtils.quoteDdlLiteral(comment == null ? "" : comment, "表注释");
            return List.of(sql);
        }

        List<String> statements = new ArrayList<>(10);
        statements.add("CREATE TABLE " + quotedTableName + " (\n" +
                "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                "  \"flow_instance_id\" BIGINT,\n" +
                "  \"tenant_id\" VARCHAR(32),\n" +
                "  \"crt_time\" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
                "  \"crt_user\" VARCHAR(32) NOT NULL,\n" +
                "  \"upd_time\" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n" +
                "  \"upd_user\" VARCHAR(32),\n" +
                "  \"deleted\" BOOLEAN NOT NULL DEFAULT FALSE\n" +
                ")");
        statements.add("COMMENT ON TABLE " + quotedTableName + " IS " +
                FlowFormSqlUtils.quotePostgresDdlLiteral(comment == null ? "" : comment, "表注释"));
        statements.add(commentOnColumn(quotedTableName, "id", "ID"));
        statements.add(commentOnColumn(quotedTableName, "flow_instance_id", "流程实例ID"));
        statements.add(commentOnColumn(quotedTableName, "tenant_id", "租户ID"));
        statements.add(commentOnColumn(quotedTableName, "crt_time", "创建时间"));
        statements.add(commentOnColumn(quotedTableName, "crt_user", "创建用户ID"));
        statements.add(commentOnColumn(quotedTableName, "upd_time", "更新时间"));
        statements.add(commentOnColumn(quotedTableName, "upd_user", "更新用户ID"));
        statements.add(commentOnColumn(quotedTableName, "deleted", "是否删除"));
        return List.copyOf(statements);
    }

    private String commentOnColumn(String quotedTableName, String columnName, String comment) {
        return "COMMENT ON COLUMN " + quotedTableName + "." + quoteIdentifier(columnName, "字段名") + " IS " +
                FlowFormSqlUtils.quotePostgresDdlLiteral(comment, "字段注释");
    }
}
